#!/usr/bin/env python
# -*- coding:utf-8 -*-
import datetime

v = ['  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 882, in _bootstrap\n    self._bootstrap_inner()\n', '  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner\n    self.run()\n', '  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run\n    self._target(*self._args, **self._kwargs)\n', '  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 628, in process_request_thread\n    self.finish_request(request, client_address)\n', '  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 357, in finish_request\n    self.RequestHandlerClass(request, client_address, self)\n', '  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 684, in __init__\n    self.handle()\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 155, in handle\n    handler.run(self.server.get_app())\n', '  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 137, in run\n    self.result = application(self.environ, self.start_response)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__\n    return self.application(environ, start_response)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__\n    response = self.get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response\n    response = self._middleware_chain(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner\n    response = get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner\n    response = get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner\n    response = get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner\n    response = get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner\n    response = get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner\n    response = get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner\n    response = get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__\n    response = self.get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner\n    response = get_response(request)\n', '  File "/Users/wupeiqi/PycharmProjects/luffycity/api/middlewares/base.py", line 14, in __call__\n    response = self.get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner\n    response = get_response(request)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view\n    return view_func(*args, **kwargs)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view\n    return self.dispatch(request, *args, **kwargs)\n', '  File "/Users/wupeiqi/py_virtual_env/luffyenv/lib/python3.5/site-packages/rest_framework/views.py", line 488, in dispatch\n    response = handler(request, *args, **kwargs)\n', '  File "/Users/wupeiqi/PycharmProjects/luffycity/api/views/order.py", line 296, in post\n    print(traceback.format_stack())\n']
for item in v:
    print(item)